### ISSUE TITLE
sbt compile fails

### ISSUE THREAD

**Issue by wdduncan** [balhoff/arachne#26]
I tried to compile arache using using `sbt compile` command. Running scalaVersion=2.12, sbtVersion=1.0, on OS X 10.15 (Catalina).

Received the following errors:
```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-native-packager;1.3.19: Resolution failed several times for dependency: com.typesafe.sbt#sbt-native-packager;1.3.19 {compile=[default(compile)]}:: 
[error] 	typesafe-ivy-releases: unable to get resource for com.typesafe.sbt#sbt-native-packager;1.3.19: res=https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.3.19/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for com.typesafe.sbt#sbt-native-packager;1.3.19: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.3.19/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by balhoff** [comment]
This works for me locally. Maybe because I have that dependency in my local cache. But I also tried a build on travis, and it worked: https://travis-ci.org/balhoff/arachne/builds/604976914?utm_source=github_status&utm_medium=notification

Maybe a network glitch for you?

**Comment by balhoff** [comment]
@wdduncan did this ever work for you?

**Comment by wdduncan** [comment]
Unfortunately, this is still not working. The command `sbt compile` results in error:
```
error: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/null)
[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
```
sbt version: 1.3.4
OS X version: 10.15.1
java version: 13.0.1

**Comment by balhoff** [comment]
Oh I see, I think your java is too new. I’m not sure the scala ecosystem is ready for >11.

**Comment by wdduncan** [comment]
Ok. I'll do some googling on how to run scala with older version of java.

**Comment by balhoff** [comment]
On Mac, you can install multiple versions, then set `JAVA_HOME` to the location of whichever installed folder you want.

**Comment by wdduncan** [comment]
Setting `JAVA_HOME` to java 11 works.  You can also use `sbt -java-home`. Here is an example that worked for me:
```
sbt -java-home /Library/Java/JavaVirtualMachines/jdk-11.0.5.jdk/Contents/Home/ compile
```
